### PR TITLE
Standard input

### PR DESCRIPTION
**Pull request by johnstevenson**

### CODE REVIEW

**Comment by johnstevenson** [comment]
@weirdan Ta for the input, but you don't sound over-enthused! I wanted to use your suggestion of "trusting" anything from setMainScript, but it would have broken bc if it didn't work (and an error was thrown), so this is a compromise.

I'm in two minds about your other suggestion to use `debug_backtrace`. It may well make the Phar::interceptFileFuncs test redundant (although I haven't tested this yet), but it would also sort of make setMainScript redundant as well (apart from your use case, possibly?). Obviously I wouldn't remove it, bit I'm struggling to find a way of describing why it is there if `debug_backtrace` is going to do its work. Any thoughts?

**Comment by weirdan** [comment]
> but you don't sound over-enthused!

Well, [one-line project turned into 20 lines](https://github.com/weirdan/run-without-xdebug/compare/1.0.0...post-1.1-fixes) in just about a month, and since the goal of that project is exactly the same as stated for xdebug-handler, only in a form of cli utility, this suggest that xdebug-handler is going in some other direction than I anticipated. It's bearable so far, but the tendency doesn't look exactly exciting :smiley: .

> but it would also sort of make setMainScript redundant as well (apart from your use case, possibly?)

Actually, it turns out `debug_backtrace()` does not return main script when called from `auto_prepend_file` (I hoped it would, but it doesn't). So it doesn't really help me at all, neither would it work for xdebug-handler robustly (as I consider my use case to be valid generally for xdebug-handler, albeit being a fringe one).

> bit I'm struggling to find a way of describing why it [`setMainScript`] is there

Now that's an easy one to justify: it's a manual override, for when the library consumer knows better. Exactly the thing I would expect from a decent library.

**Comment by johnstevenson** [comment]
So is that a 'no' for `debug_backtrace()` (and leaving the PR as it is )?

**Comment by johnstevenson** [comment]
@weirdan I've incorporated `debug_backtrace` as it works when Phar::interceptFileFuncs screws things up and it handles `chdir()`.

If you are happy with this (provided you can find the right level of enthusiasm of course!) do you think it could be a bug-fix release (as the standard input stuff never worked anyway) or should I bump it to 1.2.0?

**Comment by weirdan** [comment]
Works for me. I would prefer 1.2, as I already blacklisted 1.1.x (dunno what I was thinking).

**Pull request merged**
