### PR TITLE
Tweak proc_open and fix Windows command

### PR DESCRIPTION
**Pull request by johnstevenson**
Removes polling (let's hope this works!) and fixes the command line on Windows.

@Seldaek @ktomk Please test with your setups. Thanks.

### CODE REVIEW

**Review by ktomk — APPROVED** [review]
Done with review. Ubuntu 18.04 LTS PHP 5.6  - 8.0 (RC3) LGTM.

**Comment by Seldaek** [comment]
Looks good to me too, thanks!

**Comment by Seldaek** [comment]
I released 1.4.5 here and tweaked things on the composer end in https://github.com/composer/composer/commit/cc536c7f45e656989f987f6eea5139a76beb4419 - added the fstat fallback just in case, and now checking STDIN and not STDOUT to decide whether we are in interactive mode, which is more accurate.

**Comment by johnstevenson** [comment]
Cool. On the Composer end, you might not always have STDIN etc defined of course.

My turn to nag: what about that installer PR?

**Comment by Seldaek** [comment]
What do you mean might not always have STDIN defined? I guess in web SAPIs they would not be there, so rather check with defined()?

I'll try to look at installer PR later it's definitely on my list but yeah new stuff keeps coming.

**Comment by johnstevenson** [comment]
The constants are not defined in command line/interactive code as I recall. It's in the manual somewhere.

**Comment by Seldaek** [comment]
Ok I hope this is bulletproof enough :) https://github.com/composer/composer/commit/595c4c6f7526cb7227e584b7219b30c0c0c41cba

**Comment by johnstevenson** [comment]
Tedious, isn't it! That looks good.

**Comment by ktomk** [comment]
>  now checking STDIN and not STDOUT to decide whether we are in interactive mode, which is more accurate

It's hard to get this accurate with the broken abstraction in symfony process TTY mode. You have to choose one over the other. In my original report (composer `cat` script) IIRC I had to do the STDOUT check for the pipe as STDIN was TTY (and fine thought when testing).

At the end of the day my guess is to check both and if any of these is not TTY to not process out bound to TTY for all (TTY mode false).

This is also what I would normally intend, when piping, not or only very little interaction (e.g. break w/ ctrl+C when going south).

But it's late I have to double check this, it's in my first tests.

The sequence

~~~
defined('STDIN') ? STDIN : fopen('php://stdin', 'r')
~~~
Having something [similar as well](https://github.com/ktomk/pipelines/blob/master/src/bootstrap.php#L12) and got no complaints.

The code is using `constant($CONST_NAME_STRING_EXPRESSION)` thought. Isn't that required? Or too much of pre-caution my own?

Anyway, checked the causes back in PHP bug tracker some weeks ago again, from what I re-learned it's kind of an edge case and more recent PHP versions don't have this issue (or Phpunit had some workarounds for the phpt test-runner). From one of my notes:

> on / since some php version/s STDOUT of these three [IN/OUT/ERR] might not be available
> in the CLI SAPI when php code is passed to the php binary via standard
> input (PHP-Bug-43283)

* Ref: https://bugs.php.net/bug.php?id=43283

Will report TTY check suffice on STDOUT / STDIN in the composer tracker.

**Comment by Seldaek** [comment]
Right, with the current code it checks stdin for interactivity, then stout for tty execution, but if non interactive it anyway doesn't try tty execution. So I think it's checking both for the tty subprocess use case at least.

**Pull request merged**
