### PR TITLE
Report status output with -vvv option

### PR DESCRIPTION
**Pull request by johnstevenson**
This is something I wanted to add to the original, but it always seemed too much work with too many changes. Unfortunately this PR is not that easy to read, although the 2 new classes (Process and Status) and most of the XdebugHandler changes are clear.

The end result looks like this, when xdebug is loaded:

xdebug-handler-output

And this, when it is not:

xdebug-handler-output-none

And this, if there is an error (or PHP < 5.4):

xdebug-handler-output-error

And this, if xdebug is allowed:

xdebug-handler-output-allow

The only downside is that it has increased the code-size (by 50%). I personally think it is worth it, but I'd like to hear what others think.

### CODE REVIEW

**Comment by Seldaek** [comment]
I'm really not too keen on the duplication of shell color management here. I understand you probably don't want a dependency on symfony/console for a generic thing like this, but then maybe it could be a wrapper that accepts an symfony/console input/output  and if that's provided it will output status info, if not it just stays quiet and people can roll their own status output if they need? Or alternatively just do it without color and escaping and whatnot, simple argv check + black/white output. I think it'd be good enough really. The colors don't bring that much and they might even clash with whatever color scheme the app is using.

**Comment by weirdan** [comment]
IMHO it's too invasive. I don't think xdebug handler should interfere with output, unless *specifically* asked by the client *app* (not the end user running the app). Can't it just accept a logger, possibly PSR Logger interface, and log everything it thinks it needs to log there? Then it will be app's decision, and it would be able to use '-vvv' option however it wants. Also you wouldn't need to handle cli colors, as that would become responsibility of the external logger.

**Comment by johnstevenson** [comment]
@Seldaek Yup, that's fine. The simplest way would be to not use colors, so I'll change it.

@weirdan The point of the -vvv flag is to allow the end-user to request more information (debug level output) presumably to diagnose a problem. The client app is not in a position to make that decision.

**Comment by johnstevenson** [comment]
Now in glorious monochrome:

xdebug-handler-output-mono

**Comment by Seldaek** [comment]
Still has some color support code in there though just in case you missed it :)

**Comment by johnstevenson** [comment]
If you mean `Process::supportsColor` then that is needed for using the colorOption (and has been there since the first commit, to replace `Symfony\Component\Console\Output\ConsoleOutput`) ???

**Comment by Seldaek** [comment]
I didn't realize that.. Doing this using symfony/console's StreamOutput would be much better IMO to avoid duplicating that but anyway maybe it's a cost we have to pay to make this available to others.

**Comment by johnstevenson** [comment]
Well, it was a cost that we paid very early on (https://github.com/composer/composer/commit/cfaa122ade9b5bb474a71cefd7dcbf2a713c029a#diff-fc0630666d6226318ea87b11459d0d59) before we used the symfony component. And ours is more up to date.

Let me know if you are happy for me to merge this or not.

Incidentally, could you add "Restart a CLI process without loading the xdebug extension." to the repo description and fix the appveyor build badge: I don't have the access rights - thanks.

**Comment by Seldaek** [comment]
I haven't reviewed in depth but it seems fine to me on the surface the PR. Will do the rest yes.

**Comment by johnstevenson** [comment]
Thanks, I'll merge it (and it will probably be easier to spot any glaring code anomalies/improvements that we can fix later).

**Comment by felixfbecker** [comment]
@johnstevenson 

> The point of the -vvv flag is to allow the end-user to request more information (debug level output) presumably to diagnose a problem. The client app is not in a position to make that decision.

I don't understand this argument at all. Why is the application not in a position to do that? The XDebugHandler is invoked in PHP code of the application. There any developer can decide to parse command line arguments or persist a loglevel configured through other mechanisms (env vars, settings file, whatever) and pass a PSR7 Logger interface to redirect the logs wherever needed.
I am using the XDebugHandler in a language server that speaks an IPC protocol. Logging anything to STDOUT because some CLI flag was set is fatal because it would violate the IPC protocol. This should not be the xdebughandler's responsibility.

**Comment by johnstevenson** [comment]
@felixfbecker 

> I don't understand this argument at all. Why is the application not in a position to do that

The _verbose_ flag is set by the end-user because they specifically want to see some/more output than the program normally provides (often using the `--verbose` long option, the simple `-v` switch - which of course for some programs outputs version info - or  multiple -v options to increase  the verbosity). It is the end-user's decision to use it, not the application's.

**Comment by weirdan** [comment]
> The verbose flag is set by the end-user because they specifically want to see some/more output…

… of the application they run. And it's application responsibility to honor or disregard that request as well as any other options and include (or not) the output of the libraries (xdebug handler) it uses. And it's application that's in best position to know what should be on its STDOUT. Felix mentioned IPC (that should generate valid JSON, I believe), someone else may generate checkstyle XML output or PNG images.

**Comment by weirdan** [comment]
> So why would a user run an application that outputs a PNG image with the verbose option set to debug level anyway?

To start with, it's not 'verbose', it's '-vvv' flag that could be used for some different purpose (vivid vertical video, as a contrived example). Even if does mean 'verbose' it doesn't necessary mean 'write messages to stdout', as normally well-behaved programs send debug output to std**err** (or elsewhere, e.g. file or syslog). And then library shouldn't concern itself with all of this anyway, because both cli args and I/O streams are "owned" by the app, and it's up to the app to decide on the argument names, argument handling, what to output to what file descriptor and so on.

> If your application is worried about this happening then it should take appropriate action itself, surely?

Why do you need to add something that app would have to circumvent, when you could have done the right thing and not add it in the first place? Or add it in a simpler and more flexible way (like proposed logger dep), with less code to write and maintain?

**Comment by johnstevenson** [comment]
> To start with, it's not 'verbose', it's '-vvv' flag that could be used for some different purpose (vivid vertical video, as a contrived example). Even if does mean 'verbose' it doesn't necessary mean 'write messages to stdout', as normally well-behaved programs send debug output to stderr (or elsewhere, e.g. file or syslog). 

Command-line short options (ie those that use the `-` prefix, rather than the long option `--` prefix) can be grouped together, so if given a set of options a, b and c, you can invoke more than one of them by using either `-a -c` or `-ac`. This behavior has been around since the first `getopt` implementations in the early 1980s.

Therefore `-v` means use the `v` option, `-vv` means use the `v` option twice, etc. This is pretty standard and is used by programs such as Git, ssh, cp etc to write messages to stdout.

If your program does not advertise a `-vvv` option then why would your users use it? Or why can you not do:

```php
    if ($index = array_search('-vvv', $_SERVER['argv'])) {
        array_splice($_SERVER['argv'], $index, 1);
    }
```
However, the above would be a pain and this is clearly an issue to you both (and I am equally clearly not getting it!) so a possible solution would be to offer PSR3 logging as well:

```php
$xdebug = new XdebugHandler('app');
$xdebug->setLogger($logger);
// or to disable any user-initiated output 
$xdebug->setLogger(null);
$xdebug->check();
```
Do you guys implement logging for your use-cases?

**Comment by weirdan** [comment]
> Therefore -v means use the v option, -vv means use the v option twice, etc. This is pretty standard and is used by programs such as Git, ssh, cp etc to write messages to stdout.

Yep, that's the common usage. However cli args style and meaning should be apps decision.

> If your program does not advertise a -vvv option then why would your users use it?

Oh, that's double-edged argument: why add an option that users won't be using? 😆 If `composer/composer` needs it you could do it there (and advertise appropriately), can't you?

> Do you guys implement logging for your use-cases?

Sure.

For php-langserver (Felix's use case, I believe) it would be natural to relay all logs using telemetry to the parent process (VSCode or other editor/IDE).

> so a possible solution would be to offer PSR3 logging as well:

As long as it allows to prevent interpreting argv and polluting I/O streams it would be fine. However, assuming that mechanism is in place, don't you think you could use it as well for what you need (in composer?) ? 

> However, the above would be a pain and this is clearly an issue to you both (and I am equally clearly not getting it!)

From my perspective, you're trying to address legitimate concern (logging) in a somewhat roundabout way, so as a fellow programmer I'm trying to advise you to solve it in a different and, I believe, better (easier and more flexible) way.

**Pull request merged**
