### PR TITLE
Use custom environment variables

### PR DESCRIPTION
**Pull request by johnstevenson**
This implements https://github.com/composer/xdebug-handler/issues/5

### CODE REVIEW

**Comment by johnstevenson** [comment]
Perhaps `$id` would be better than `$appName` name for the constructor param?

**Comment by alcohol** [comment]
I'm not sure how I feel about using the constructor for this. It isn't very intuitive. I'd rather have some sane/safe defaults, and a method that allows the user to specifically override the environment variable names. How would you feel about that?

**Comment by johnstevenson** [comment]
@alcohol Firstly I agree about making the class final, if we can. Regarding the use of the constructor, I have taken the approach that custom environment variables are an integral part of putting XdebugHandler into a separate package, rather than just an _enhancement_.

My reasoning is that XdebugHandler could be used by more than one app in the same parent process, for example when calling a script from composer. By enforcing app-specific environment variables you hand over control to the implementation and, most importantly, never have to worry about any conflicts that might or might not occur.

I chose the prefixing approach to the names as an understandable way to extend what is already out there in the wild (`COMPOSER_ALLOW_XDEBUG, COMPOSER_ORIGINAL_INIS`, `APP_ALLOW_XDEBUG, APP_ORIGINAL_INIS`). And also to keep things simple.

They might not be pretty but quite a bit of thought went into them! Have you got any specific examples of an environment name that would be 'better', or is it simply the case of providing flexibility?

Your thoughts on the above, please.

**Comment by alcohol** [comment]
> or is it simply the case of providing flexibility

Mostly this.

I'd prefer to impose as few restrictions as possible (nor enforce any conventions or guidelines). If someone wants to call their environment variable "FUBAR", then by all means, let them call it so.

**Comment by johnstevenson** [comment]
@alcohol Okay, but would `FUBAR_ALLOW_XDEBUG` really be too much of an imposition? I personally would not feel too repressed because of this.

Also, what was your take on the environment variables being "integral to", rather than an "enhancement of", supposition (particularly in regards to sub-process conflicts)?

**Comment by johnstevenson** [comment]
@Seldaek Be nice to have your input here, if you are not too busy.

**Comment by Seldaek** [comment]
Current PR seems fine to me really.. Not that strong an opinion on env var names :p

**Comment by johnstevenson** [comment]
Ok thanks. I'll merge this later and see how it goes, as the environment variable syntax is already being used used:

https://github.com/phan/phan/blob/c6775f9d308f69241af7c83df25d1540b3aca5db/src/Phan/Library/Composer/XdebugHandler.php#L45

**Pull request merged**
